fixtures:
  repositories:
    # Required because of https://github.com/puppetlabs/puppetlabs-apache/pull/803
    apache: 
      repo: 'git://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.1.1'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    rvm: 'git://github.com/maestrodev/puppet-rvm.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    puppet_stack: "#{source_dir}"
