fixtures:
  repositories:
    apache: 'git://github.com/puppetlabs/puppetlabs-apache.git'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    rvm: 'git://github.com/maestrodev/puppet-rvm.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    puppet_stack: "#{source_dir}"
